//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_net.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TP_net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compras {
            get {
                object obj = ResourceManager.GetObject("compras", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logOUT {
            get {
                object obj = ResourceManager.GetObject("logOUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MostarPass {
            get {
                object obj = ResourceManager.GetObject("MostarPass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;TIENDA GIN - Comprobante de Compra&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Comprobante de Compra&lt;/h1&gt;
        ///    &lt;p&gt;Usuario: &lt;span id=&quot;usuario&quot;&gt;@USUARIO&lt;/span&gt;&lt;/p&gt;
        ///    &lt;p&gt;N° de compra: &lt;span id=&quot;idcompra&quot;&gt;@NCOMPRA&lt;/span&gt;&lt;/p&gt;
        ///    &lt;p&gt;Fecha: &lt;span id=&quot;fecha&quot;&gt;@FECHA&lt;/span&gt;&lt;/p&gt;
        ///
        ///    &lt;table border=&quot;1&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;ID Línea&lt;/th&gt;
        ///            &lt;th&gt;Nombre del Producto&lt;/th&gt;
        ///            &lt;th&gt;Marca&lt;/th&gt;
        ///            &lt;th&gt;Cantidad Pedida&lt;/th&gt;
        ///            &lt;th&gt;Precio U [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantillahtml {
            get {
                return ResourceManager.GetString("plantillahtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Informe de Ventas&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table {
        ///            width: 100%;
        ///            border-collapse: collapse;
        ///        }
        ///
        ///        table, th, td {
        ///            border: 1px solid black;
        ///        }
        ///
        ///        th, td {
        ///            padding: 8px;
        ///            text-align: left;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Informe de Ventas - TIENDA GIN&lt;/h1&gt;
        ///
        ///    &lt;table&gt;
        ///        &lt;thead&gt;
        ///            &lt;tr&gt;
        ///                &lt;th&gt;ID Venta&lt;/th&gt;
        ///         [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantillaVendedor {
            get {
                return ResourceManager.GetString("plantillaVendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shopping {
            get {
                object obj = ResourceManager.GetObject("shopping", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
